import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <main>
            <header className="navbar bg-[#ece3ca] shadow-sm">
                <section className="flex-1">
                    <a className="btn btn-ghost text-xl hover:bg-[#cfc4a3]" href={"/"}>Info</a>
                    <a className="btn btn-ghost text-xl hover:bg-[#cfc4a3]" href={"/history"}>History</a>
                </section>
                <section className="flex-none">
                    <h1>JavaZone</h1>
                </section>
            </header>
            {children}
        </main>
        <footer className="dock dock-xs bg-[#ece3ca]">
            <a href={"https://www.java.no"}>Made by javaBin</a>
            <a href={"https://java.no/principles"}>Code of conduct</a>
        </footer>
        </body>
        </html>
    );
}
